// Generated by CoffeeScript 1.7.1
(function() {
  var init;

  init = function() {
    'use strict';
    return $('.lb-trigger').on('click', function(e) {
      var image_href, lightbox, next_image, previous_image, slideNum;
      e.preventDefault();
      image_href = $(this).attr("href");
      slideNum = $('.lb-trigger').index(this) + 1;
      lightbox = "<div class='lightbox'> <button class='btn-tiny close'>Close Me</button> <div class='lb-content'> <div class='lb-nav'> <button class='lb-prev btn-norm'> < </button> <button class='lb-next btn-norm'> > </button> </div> <figure> <figcaption> <h3>" + gon.imageName[slideNum - 1] + " </h3> <p> " + gon.imageText[slideNum - 1] + " </p> </figcaption> </figure> </div> </div>";
      $('body').append(lightbox);
      $('.grid-box').find('.lb-trigger').each(function() {
        var $href;
        $href = $(this).attr('href');
        if (image_href === $href) {
          return $('.lb-content').prepend($('<img src="' + $href + '">').show());
        } else {
          return $('.lb-content').prepend($('<img src="' + $href + '">').hide());
        }
      });
      if (slideNum === $('.lb-trigger').length) {
        next_image = $('.lb-trigger').first();
        previous_image = $(this).closest('li').prev('li').find('.lb-trigger');
      } else if (slideNum === 1) {
        next_image = $(this).closest('li').next('li').find('.lb-trigger');
        previous_image = $('.lb-trigger').last();
      } else {
        next_image = $(this).closest('li').next('li').find('.lb-trigger');
        previous_image = $(this).closest('li').prev('li').find('.lb-trigger');
      }
      $('.lightbox').click(function(event) {
        $(this).fadeOut(300);
        return $(this).remove();
      });
      $('.lb-prev').click(function() {
        $('.lightbox').click();
        return $(previous_image).click();
      });
      $('.lb-next').click(function() {
        $('.lightbox').click();
        return $(next_image).click();
      });
      return $(this).keypress(function(e) {
        var evt, keycode;
        e.stopImmediatePropagation();
        e.preventDefault();
        evt = e ? e : window.event;
        keycode = evt.keyCode ? evt.keyCode : evt.which;
        if (keycode === 37 || keycode === 38) {
          return $('.lb-prev').click();
        } else if (keycode === 39 || keycode === 40) {
          return $('.lb-next').click();
        } else if (keycode === 27) {
          return $('.lightbox').click();
        }
      });
    });

  $(document).ready(init);

  $(document).on('page:load', init);

}).call(this);
